# Generated by Django 5.2.14 on 2026-09-28 02:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def preserve_legacy_state(apps, schema_editor):
    """Keep ambiguous progress and dates without manufacturing playthroughs."""
    Game = apps.get_model("app", "Game")
    DiaryEntry = apps.get_model("app", "DiaryEntry")
    MediaLike = apps.get_model("app", "MediaLike")
    for game in Game.objects.using(schema_editor.connection.alias).iterator():
        diary_exists = DiaryEntry.objects.using(schema_editor.connection.alias).filter(user_id=game.user_id, item_id=game.item_id).exists()
        game.completed_manually = game.status == "Completed" and not diary_exists
        kind = "undated_completion" if game.completed_manually else "legacy_completion" if game.status == "Completed" else "direct_status"
        game.status_history = [{"status": game.status, "kind": kind}]
        game.like_is_independent = MediaLike.objects.using(schema_editor.connection.alias).filter(user_id=game.user_id, item_id=game.item_id).exists()
        game.save(update_fields=["completed_manually", "status_history", "like_is_independent"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_media_series_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='completed_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='imported_lifetime_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='imported_lifetime_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='like_is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='like_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='game',
            name='rating_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='game',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='completed_manually',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='imported_lifetime_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='imported_lifetime_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='like_is_independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='like_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='rating_source',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.diaryentry'),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='status_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In progress', 'In Progress'), ('Planning', 'Planning'), ('Paused', 'Paused'), ('Dropped', 'Dropped')], max_length=20)),
                ('origin', models.CharField(choices=[('live', 'Tracked playthrough'), ('direct_log', 'Direct completion')], default='live', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('percentage', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('first_progress_on', models.DateField(blank=True, null=True)),
                ('minutes_updated_on', models.DateField(blank=True, null=True)),
                ('percentage_updated_on', models.DateField(blank=True, null=True)),
                ('minutes_linked', models.BooleanField(default=False)),
                ('percentage_linked', models.BooleanField(default=False)),
                ('mutation_id', models.UUIDField(blank=True, null=True)),
                ('completion_mutation_id', models.UUIDField(blank=True, null=True)),
                ('completion_diary_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_playthrough', to='app.diaryentry')),
                ('related_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playthroughs', to='app.game')),
            ],
            options={
                'ordering': ['related_game', '-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='current_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.gamesession'),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='current_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='app.gamesession'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['In progress', 'Paused'])), fields=('related_game',), name='app_game_one_open_playthrough'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('mutation_id__isnull', False)), fields=('related_game', 'mutation_id'), name='app_game_unique_start_mutation'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.UniqueConstraint(condition=models.Q(('completion_mutation_id__isnull', False)), fields=('related_game', 'completion_mutation_id'), name='app_game_unique_log_mutation'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__isnull', True), ('percentage__lte', 100), _connector='OR'), name='app_game_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='app_game_dates_ordered'),
        ),
        migrations.AddConstraint(
            model_name='gamesession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('origin', 'live'), _negated=True), ('start_date__isnull', False), _connector='OR'), name='app_game_live_start_required'),
        ),
        migrations.RunPython(preserve_legacy_state, migrations.RunPython.noop),
    ]
