# Generated by Django 5.2.14 on 2026-09-28 02:23

import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


def archive_duplicates(apps, schema_editor):
    """Retain every old row and its history; expose the newest per user/title."""
    Game = apps.get_model("app", "Game")
    seen = set()
    for game in Game.all_objects.using(schema_editor.connection.alias).order_by("user_id", "item_id", "-created_at", "-id").iterator():
        key = (game.user_id, game.item_id)
        if key in seen:
            Game.all_objects.using(schema_editor.connection.alias).filter(pk=game.pk).update(legacy_archived=True)
        seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_game_playthrough_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['user', 'item', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='game',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='legacy_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='legacy_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(archive_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_archived', False)), fields=('user', 'item'), name='app_game_unique_current_tracking'),
        ),
    ]
