from django.urls import path

from api.views.auth import (
    AppleAuthView,
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetView,
    RefreshView,
    RegisterView,
)
from api.views.diary import DiaryDetailView, DiaryLikeView, DiaryListView, DiaryTagsView
from api.views.health import HealthView, MetaView
from api.views.imports import (
    ExportCSVView,
    ImportScheduleView,
    ImportSourceView,
    ImportsView,
    ImportTaskView,
)
from api.views.lists import (
    FeaturedListsView,
    ListCollaboratorDetailView,
    ListCollaboratorsView,
    ListDetailView,
    ListItemDetailView,
    ListItemsReorderView,
    ListItemsView,
    ListLikeView,
    ListPeopleReorderView,
    ListPeopleView,
    ListPersonDetailView,
    ListsView,
)
from api.views.media import (
    AniListReviewsView,
    BookSeriesDetailView,
    CommunityStatsView,
    CompanyAnimeOptionsView,
    CompanyAnimeView,
    CompanyDetailView,
    CompanyGameOptionsView,
    CompanyGamesView,
    FilterOptionsView,
    ManualMediaView,
    MediaBackdropPreferenceView,
    MediaBackdropsView,
    MediaDetailView,
    MediaDiscoverView,
    MediaExternalRatingsView,
    MediaLogoPreferenceView,
    MediaLogosView,
    MediaPosterPreferenceView,
    MediaPostersView,
    MediaReviewsView,
    MediaSearchView,
    MediaSourcesView,
    MusicBasicDetailView,
    MusicEnrichmentDetailView,
    MusicRecordingDetailView,
    PeopleSearchView,
    PersonCompletionView,
    PersonDetailView,
    SeasonDetailView,
    SeasonEpisodesView,
    TVSeasonsView,
)
from api.views.profile import (
    AvatarView,
    HOFItemView,
    LikedMediaView,
    MeHOFView,
    MeView,
    PasswordChangeView,
    PreferencesView,
    ProfileBackdropView,
    PublicProfileView,
    UserHOFView,
    UserSearchView,
)
from api.views.social import (
    BlockView,
    FeedView,
    FollowRequestActionView,
    FollowRequestsView,
    FollowView,
    GenericLikeView,
    UserActivityView,
)
from api.views.stats import (
    MyStatsMostLoggedView,
    MyStatsSummaryView,
    UserStatsMostLoggedView,
    UserStatsSummaryView,
)
from api.views.tracking import (
    BookCompleteView,
    BookJourneyView,
    BookProgressView,
    EpisodeWatchView,
    GameCompleteView,
    GamePlaythroughView,
    GameProgressView,
    SeasonStartView,
    SeasonWatchView,
    TrackingActionView,
    TrackingDetailView,
    TrackingListView,
    TVStartView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="api-health"),
    path("meta/", MetaView.as_view(), name="api-meta"),
    path("auth/register/", RegisterView.as_view(), name="api-register"),
    path("auth/login/", LoginView.as_view(), name="api-login"),
    path("auth/refresh/", RefreshView.as_view(), name="api-refresh"),
    path("auth/logout/", LogoutView.as_view(), name="api-logout"),
    path("auth/password-reset/", PasswordResetView.as_view(), name="api-password-reset"),
    path("auth/password-reset/confirm/", PasswordResetConfirmView.as_view(), name="api-password-reset-confirm"),
    path("auth/apple/", AppleAuthView.as_view(), name="api-apple"),
    path("me/", MeView.as_view(), name="api-me"),
    path("me/avatar/", AvatarView.as_view(), name="api-me-avatar"),
    path("me/profile-backdrop/", ProfileBackdropView.as_view(), name="api-me-profile-backdrop"),
    path("me/liked-media/", LikedMediaView.as_view(), name="api-me-liked-media"),
    path("me/password/", PasswordChangeView.as_view(), name="api-me-password"),
    path("me/preferences/", PreferencesView.as_view(), name="api-me-preferences"),
    path("me/hof/", MeHOFView.as_view(), name="api-me-hof"),
    path("me/hof/<str:media_type>/", HOFItemView.as_view(), name="api-me-hof-item"),
    path("media/search/", MediaSearchView.as_view(), name="api-media-search"),
    path("filter-options/", FilterOptionsView.as_view(), name="api-filter-options"),
    path("media/discover/", MediaDiscoverView.as_view(), name="api-media-discover"),
    path("media/sources/", MediaSourcesView.as_view(), name="api-media-sources"),
    path("media/manual/", ManualMediaView.as_view(), name="api-media-manual"),
    path("media/<str:source>/tv/<str:media_id>/seasons/", TVSeasonsView.as_view(), name="api-tv-seasons"),
    path("media/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/", SeasonDetailView.as_view(), name="api-season-detail"),
    path("media/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/episodes/", SeasonEpisodesView.as_view(), name="api-season-episodes"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/posters/", MediaPostersView.as_view(), name="api-media-posters"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/poster/", MediaPosterPreferenceView.as_view(), name="api-media-poster"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/backdrops/", MediaBackdropsView.as_view(), name="api-media-backdrops"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/backdrop/", MediaBackdropPreferenceView.as_view(), name="api-media-backdrop"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/logos/", MediaLogosView.as_view(), name="api-media-logos"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/logo/", MediaLogoPreferenceView.as_view(), name="api-media-logo"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/community/", CommunityStatsView.as_view(), name="api-media-community"),
    path("media/<str:source>/<str:media_type>/<str:media_id>/reviews/", MediaReviewsView.as_view(), name="api-media-reviews"),
    path(
        "media/<str:source>/<str:media_type>/<str:media_id>/anilist-reviews/",
        AniListReviewsView.as_view(),
        name="api-media-anilist-reviews",
    ),
    path(
        "media/<str:source>/<str:media_type>/<str:media_id>/external-ratings/",
        MediaExternalRatingsView.as_view(),
        name="api-media-external-ratings",
    ),
    path(
        "media/musicbrainz/music/<uuid:release_group_mbid>/basic/",
        MusicBasicDetailView.as_view(),
        name="api-music-basic-detail",
    ),
    path(
        "media/musicbrainz/music/<uuid:release_group_mbid>/enrichment/",
        MusicEnrichmentDetailView.as_view(),
        name="api-music-enrichment-detail",
    ),
    path(
        "media/musicbrainz/music/<uuid:release_group_mbid>/recordings/<uuid:recording_mbid>/",
        MusicRecordingDetailView.as_view(),
        name="api-music-recording-detail",
    ),
    path("media/<str:source>/<str:media_type>/<str:media_id>/", MediaDetailView.as_view(), name="api-media-detail"),
    path("people/search/", PeopleSearchView.as_view(), name="api-people-search"),
    path(
        "people/<str:source>/<str:person_id>/completion/",
        PersonCompletionView.as_view(),
        name="api-person-completion",
    ),
    path("people/<str:source>/<str:person_id>/", PersonDetailView.as_view(), name="api-person-detail"),
    path("series/<str:source>/<str:series_id>/", BookSeriesDetailView.as_view(), name="api-book-series-detail"),
    path("companies/<str:source>/<str:company_id>/", CompanyDetailView.as_view(), name="api-company-detail"),
    path(
        "companies/<str:source>/<str:company_id>/game-options/",
        CompanyGameOptionsView.as_view(),
        name="api-company-game-options",
    ),
    path(
        "companies/<str:source>/<str:company_id>/anime-options/",
        CompanyAnimeOptionsView.as_view(),
        name="api-company-anime-options",
    ),
    path(
        "companies/<str:source>/<str:company_id>/anime/",
        CompanyAnimeView.as_view(),
        name="api-company-anime",
    ),
    path("companies/<str:source>/<str:company_id>/games/", CompanyGamesView.as_view(), name="api-company-games"),
    path("tracking/", TrackingListView.as_view(), name="api-tracking-list"),
    path("tracking/<str:source>/tv/<str:media_id>/start/", TVStartView.as_view(), name="api-tv-start"),
    path("tracking/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/start/", SeasonStartView.as_view(), name="api-season-start"),
    path("tracking/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/watch/", SeasonWatchView.as_view(), name="api-season-watch"),
    path("tracking/<str:source>/tv/<str:media_id>/seasons/<int:season_number>/episodes/<int:episode_number>/watch/", EpisodeWatchView.as_view(), name="api-episode-watch"),
    path("tracking/<str:source>/game/<str:media_id>/progress/", GameProgressView.as_view(), name="api-game-progress"),
    path("tracking/<str:source>/game/<str:media_id>/complete/", GameCompleteView.as_view(), name="api-game-complete"),
    path("tracking/<str:source>/game/<str:media_id>/playthroughs/<int:playthrough_id>/", GamePlaythroughView.as_view(), name="api-game-playthrough"),
    path("tracking/<str:source>/book/<str:media_id>/progress/", BookProgressView.as_view(), name="api-book-progress"),
    path("tracking/<str:source>/book/<str:media_id>/complete/", BookCompleteView.as_view(), name="api-book-complete"),
    path("tracking/<str:source>/book/<str:media_id>/journeys/<int:journey_id>/", BookJourneyView.as_view(), name="api-book-journey"),
    path("tracking/<str:source>/<str:media_type>/<str:media_id>/actions/<str:action>/", TrackingActionView.as_view(), name="api-tracking-action"),
    path("tracking/<str:source>/<str:media_type>/<str:media_id>/", TrackingDetailView.as_view(), name="api-tracking-detail"),
    path("diary/", DiaryListView.as_view(), name="api-diary-list"),
    path("diary/tags/", DiaryTagsView.as_view(), name="api-diary-tags"),
    path("diary/<int:entry_id>/", DiaryDetailView.as_view(), name="api-diary-detail"),
    path("diary/<int:entry_id>/like/", DiaryLikeView.as_view(), name="api-diary-like"),
    path("stats/me/summary/", MyStatsSummaryView.as_view(), name="api-my-stats"),
    path("stats/me/most-logged/", MyStatsMostLoggedView.as_view(), name="api-my-stats-most-logged"),
    path("lists/", ListsView.as_view(), name="api-lists"),
    path("lists/featured/", FeaturedListsView.as_view(), name="api-featured-lists"),
    path("lists/<int:list_id>/", ListDetailView.as_view(), name="api-list-detail"),
    path("lists/<int:list_id>/items/", ListItemsView.as_view(), name="api-list-items"),
    path("lists/<int:list_id>/items/reorder/", ListItemsReorderView.as_view(), name="api-list-items-reorder"),
    path("lists/<int:list_id>/items/<int:item_id>/", ListItemDetailView.as_view(), name="api-list-item-detail"),
    path("lists/<int:list_id>/people/", ListPeopleView.as_view(), name="api-list-people"),
    path(
        "lists/<int:list_id>/people/reorder/",
        ListPeopleReorderView.as_view(),
        name="api-list-people-reorder",
    ),
    path(
        "lists/<int:list_id>/people/<int:entry_id>/",
        ListPersonDetailView.as_view(),
        name="api-list-person-detail",
    ),
    path("lists/<int:list_id>/collaborators/", ListCollaboratorsView.as_view(), name="api-list-collaborators"),
    path("lists/<int:list_id>/collaborators/<int:user_id>/", ListCollaboratorDetailView.as_view(), name="api-list-collaborator-detail"),
    path("lists/<int:list_id>/like/", ListLikeView.as_view(), name="api-list-like"),
    path("feed/", FeedView.as_view(), name="api-feed"),
    path("follow-requests/", FollowRequestsView.as_view(), name="api-follow-requests"),
    path("follow-requests/<int:request_id>/<str:action>/", FollowRequestActionView.as_view(), name="api-follow-request-action"),
    path("social/likes/", GenericLikeView.as_view(), name="api-social-likes"),
    path("imports/", ImportsView.as_view(), name="api-imports"),
    path("imports/<str:source>/", ImportSourceView.as_view(), name="api-import-source"),
    path("imports/tasks/<str:task_id>/", ImportTaskView.as_view(), name="api-import-task"),
    path("imports/schedules/<int:schedule_id>/", ImportScheduleView.as_view(), name="api-import-schedule"),
    path("exports/csv/", ExportCSVView.as_view(), name="api-export-csv"),
    path("users/search/", UserSearchView.as_view(), name="api-user-search"),
    path("users/<str:username>/", PublicProfileView.as_view(), name="api-user-profile"),
    path("users/<str:username>/hof/", UserHOFView.as_view(), name="api-user-hof"),
    path("users/<str:username>/stats/summary/", UserStatsSummaryView.as_view(), name="api-user-stats"),
    path(
        "users/<str:username>/stats/most-logged/",
        UserStatsMostLoggedView.as_view(),
        name="api-user-stats-most-logged",
    ),
    path("users/<str:username>/activity/", UserActivityView.as_view(), name="api-user-activity"),
    path("users/<str:username>/follow/", FollowView.as_view(), name="api-user-follow"),
    path("users/<str:username>/block/", BlockView.as_view(), name="api-user-block"),
]
